version: '3'

services:
  rx-api:
    image: registry.cn-shanghai.aliyuncs.com/back_end/renxin-cloud-api:${IMAGE_TAG}
    ports:
      - 4001:3000
    restart: always
    environment:
      TZ: "Asia/Shanghai"
      PORT: 3000
      DB_URL: ${DB_URL}
      REDIS_URL: ${REDIS_URL}
      PAYMENT_ENV: ${PAYMENT_ENV}
      KAFKA_BROKERS: ${KAFKA_BROKERS}
    deploy:
      mode: replicated
      replicas: 2
  rx-task:
    image: registry.cn-shanghai.aliyuncs.com/back_end/renxin-cloud-task:${IMAGE_TAG}
    restart: always
    environment:
      TZ: "Asia/Shanghai"
      DB_URL: ${DB_URL}
      REDIS_URL: ${REDIS_URL}
      PAYMENT_ENV: ${PAYMENT_ENV}
      KAFKA_BROKERS: ${KAFKA_BROKERS}
    deploy:
      mode: replicated
      replicas: 1